from .Bolsones import Bolsones as BolsonesResource
from .Bolsones import Bolson as BolsonResource
from .BolsonesPendientes import BolsonesPendientes as BolsonesPendientesResource
from .BolsonesPendientes import BolsonPendiente as BolsonPendienteResource
from .BolsonesPrevios import BolsonesPrevios as BolsonesPreviosResource
from .BolsonesPrevios import BolsonPrevio as BolsonPrevioResource
from .BolsonesVenta import BolsonesVenta as BolsonesVentaResource
from .BolsonesVenta import BolsonVenta as BolsonVentaResource
from .Clientes import Clientes as ClientesResource
from .Clientes import Cliente as ClienteResource
from .Compras import Compras as ComprasResource
from .Compras import Compra as CompraResource
from .Productos import Productos as ProductosResource
from .Productos import Producto as ProductoResource
from .Proveedores import Proveedores as ProveedoresResource
from .Proveedores import Proveedor as ProveedorResource
from .Administradores import Administradores as AdministradoresResource
from .Administradores import Administrador as AdministradorResource

